development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://knjmwyqxsednbo:MvkGVUKWb9X1P5FIKluUW093P7@ec2-23-21-96-70.compute-1.amazonaws.com:5432/d3q71susfe8rm4
